// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YohualkisTejada_AP1_P2.DAL;

#nullable disable

namespace YohualkisTejada_AP1_P2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241118031926_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YohualkisTejada_AP1_P2.Models.ArticulosModelos", b =>
                {
                    b.Property<int>("ArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticuloId"));

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("ArticuloId");

                    b.ToTable("ArticulosModelos");

                    b.HasData(
                        new
                        {
                            ArticuloId = 1,
                            Costo = 1999.99,
                            Descripcion = "Articulo 1",
                            Existencia = 51,
                            Precio = 1999.99
                        },
                        new
                        {
                            ArticuloId = 2,
                            Costo = 3999.9899999999998,
                            Descripcion = "Articulo 2",
                            Existencia = 64,
                            Precio = 9999.9899999999998
                        },
                        new
                        {
                            ArticuloId = 3,
                            Costo = 559.99000000000001,
                            Descripcion = "Articulo 3",
                            Existencia = 85,
                            Precio = 5449.9899999999998
                        },
                        new
                        {
                            ArticuloId = 4,
                            Costo = 7599.9899999999998,
                            Descripcion = "Articulo 4",
                            Existencia = 71,
                            Precio = 4599.9899999999998
                        },
                        new
                        {
                            ArticuloId = 5,
                            Costo = 5769.8000000000002,
                            Descripcion = "Articulo 5",
                            Existencia = 84,
                            Precio = 2699.5
                        });
                });

            modelBuilder.Entity("YohualkisTejada_AP1_P2.Models.Modelos", b =>
                {
                    b.Property<int>("ModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeloId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sueldo")
                        .HasColumnType("int");

                    b.HasKey("ModeloId");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("YohualkisTejada_AP1_P2.Models.ModelosDetalles", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("DetalleId");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("ModeloId");

                    b.ToTable("ModelosDetalles");
                });

            modelBuilder.Entity("YohualkisTejada_AP1_P2.Models.ModelosDetalles", b =>
                {
                    b.HasOne("YohualkisTejada_AP1_P2.Models.ArticulosModelos", "Articulos")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YohualkisTejada_AP1_P2.Models.Modelos", null)
                        .WithMany("Detalles")
                        .HasForeignKey("ModeloId");

                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("YohualkisTejada_AP1_P2.Models.Modelos", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
